# Generated by Django 6.0.1 on 2026-01-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pluginexecutionlog',
            new_name='plugins_plu_instanc_db026a_idx',
            old_name='plugins_plu_instanc_c8f9b1_idx',
        ),
        migrations.RenameIndex(
            model_name='pluginexecutionlog',
            new_name='plugins_plu_documen_1d47ee_idx',
            old_name='plugins_plu_documen_e7b1a2_idx',
        ),
        migrations.RenameIndex(
            model_name='pluginexecutionlog',
            new_name='plugins_plu_status_21cd21_idx',
            old_name='plugins_plu_status_a3d4e5_idx',
        ),
    ]
