# Generated by Django 6.0.1 on 2026-01-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_rename_plugins_plu_instanc_c8f9b1_idx_plugins_plu_instanc_db026a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='affinda_data_source',
            field=models.CharField(blank=True, help_text='Affinda data source identifier (for data source components)', max_length=255),
        ),
        migrations.AlterField(
            model_name='plugincomponent',
            name='component_type',
            field=models.CharField(choices=[('importer', 'Importer'), ('preprocessor', 'Pre-Processor'), ('postprocessor', 'Post-Processor'), ('datasource', 'Data Source')], max_length=32),
        ),
    ]
