# Generated by Django 6.0.1 on 2026-01-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_plugininstance_affinda_data_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique identifier for this source', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name for this source', max_length=200)),
                ('url', models.URLField(help_text='Git repository URL or direct download URL', max_length=500)),
                ('source_type', models.CharField(choices=[('builtin', 'Built-in'), ('user', 'User-added')], default='user', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('is_multi_plugin', models.BooleanField(default=False, help_text='Whether this source contains multiple plugins')),
                ('manifest_data', models.JSONField(blank=True, default=dict, help_text='Cached manifest data from the source')),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time we checked for updates', null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, help_text='Last time we successfully fetched manifest', null=True)),
                ('latest_version', models.CharField(blank=True, help_text='Latest version from manifest or git tag', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Last error message if fetch failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='plugin',
            name='available_version',
            field=models.CharField(blank=True, help_text='Latest available version from source', max_length=50),
        ),
        migrations.AddField(
            model_name='plugin',
            name='installed_from_url',
            field=models.URLField(blank=True, help_text='Original URL the plugin was installed from', max_length=500),
        ),
        migrations.AddField(
            model_name='plugin',
            name='installed_version',
            field=models.CharField(blank=True, help_text='Version of the plugin when installed', max_length=50),
        ),
        migrations.AddField(
            model_name='plugin',
            name='source_path',
            field=models.CharField(blank=True, help_text='Path within the source repo (for multi-plugin repos)', max_length=200),
        ),
        migrations.AddField(
            model_name='plugin',
            name='update_available',
            field=models.BooleanField(default=False, help_text='Whether a newer version is available'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The source this plugin was installed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugins', to='plugins.pluginsource'),
        ),
    ]
