# Generated by Django 6.0.1 on 2026-01-10 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('annotation_content_type', models.CharField(blank=True, max_length=64)),
                ('organization_identifier', models.CharField(blank=True, max_length=64)),
                ('extractor', models.CharField(blank=True, max_length=64)),
                ('is_public', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('custom_identifier', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=512)),
                ('file_url', models.URLField(blank=True, max_length=1024)),
                ('state', models.CharField(blank=True, choices=[('review', 'Review'), ('complete', 'Complete'), ('archived', 'Archived')], max_length=32)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('in_review', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('validatable', models.BooleanField(default=False)),
                ('has_challenges', models.BooleanField(default=False)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_dt', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='affinda_bridge.collection')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='affinda_bridge.workspace')),
            ],
            options={
                'ordering': ['-created_dt'],
                'indexes': [models.Index(fields=['workspace', 'collection'], name='affinda_bri_workspa_06705f_idx'), models.Index(fields=['state'], name='affinda_bri_state_bccf76_idx'), models.Index(fields=['created_dt'], name='affinda_bri_created_399bff_idx'), models.Index(fields=['custom_identifier'], name='affinda_bri_custom__a91a67_idx')],
            },
        ),
    ]
