# Generated by Django 6.0.1 on 2026-01-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0002_datapoint_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_updated_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
