# Generated by Django 6.0.1 on 2026-01-12 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0003_document_last_updated_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('workspaces', 'Workspaces'), ('collections', 'Collections'), ('field_definitions', 'Field Definitions'), ('documents', 'Documents')], max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [
                    models.Index(fields=['sync_type', '-started_at'], name='affinda_bri_sync_ty_c8e6ed_idx'),
                ],
            },
        ),
    ]
