# Generated by Django 6.0.1 on 2026-01-15 06:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0004_synchistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly name for the view', max_length=255)),
                ('sql_view_name', models.CharField(blank=True, help_text='Actual SQL view name (auto-generated, sanitized)', max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the view currently exists in the database')),
                ('include_fields', models.JSONField(blank=True, default=list, help_text='List of field_definition IDs to include (empty = all)')),
                ('last_sql', models.TextField(blank=True, help_text='Last SQL statement used to create the view')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, help_text='When the view was last refreshed in the database', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Last error message if view creation failed')),
            ],
            options={
                'ordering': ['collection', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('raw_value', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RenameIndex(
            model_name='synchistory',
            new_name='affinda_bri_sync_ty_c40e22_idx',
            old_name='affinda_bri_sync_ty_c8e6ed_idx',
        ),
        migrations.AddField(
            model_name='collectionview',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_views', to='affinda_bridge.collection'),
        ),
        migrations.AddField(
            model_name='documentfieldvalue',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='affinda_bridge.document'),
        ),
        migrations.AddField(
            model_name='documentfieldvalue',
            name='field_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_values', to='affinda_bridge.fielddefinition'),
        ),
        migrations.AddIndex(
            model_name='collectionview',
            index=models.Index(fields=['collection', 'is_active'], name='affinda_bri_collect_71e985_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionview',
            index=models.Index(fields=['sql_view_name'], name='affinda_bri_sql_vie_99e986_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfieldvalue',
            index=models.Index(fields=['document', 'field_definition'], name='affinda_bri_documen_773baa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfieldvalue',
            index=models.Index(fields=['field_definition'], name='affinda_bri_field_d_91ee46_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentfieldvalue',
            constraint=models.UniqueConstraint(fields=('document', 'field_definition'), name='unique_document_field_value'),
        ),
    ]
