# Generated by Django 6.0.1 on 2026-01-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0005_collectionview_documentfieldvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_url',
            field=models.URLField(blank=True, help_text='URL to review/edit the document in Affinda', max_length=1024),
        ),
    ]
