# Generated by Django 6.0.1 on 2026-01-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0006_document_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionview',
            name='include_document_columns',
            field=models.JSONField(blank=True, default=list, help_text='List of document column names to include (empty = defaults)'),
        ),
    ]
