# Generated by Django 6.0.1 on 2026-01-15 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0007_collectionview_document_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionview',
            name='include_external_tables',
            field=models.JSONField(blank=True, default=list, help_text='List of ExternalTable IDs to include in the view'),
        ),
        migrations.CreateModel(
            name='ExternalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly name for the external table', max_length=255)),
                ('sql_table_name', models.CharField(blank=True, help_text='Actual SQL table name (auto-generated, sanitized)', max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the table currently exists in the database')),
                ('last_sql', models.TextField(blank=True, help_text='Last SQL statement used to create the table')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, help_text='Last error message if table creation failed')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tables', to='affinda_bridge.collection')),
            ],
            options={
                'ordering': ['collection', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly column name', max_length=255)),
                ('sql_column_name', models.CharField(blank=True, help_text='Actual SQL column name (auto-generated, sanitized)', max_length=63)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime')], default='text', max_length=32)),
                ('is_nullable', models.BooleanField(default=True, help_text='Whether the column allows NULL values')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which columns are displayed')),
                ('external_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='affinda_bridge.externaltable')),
            ],
            options={
                'ordering': ['external_table', 'display_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='externaltable',
            index=models.Index(fields=['collection', 'is_active'], name='affinda_bri_collect_973943_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltable',
            index=models.Index(fields=['sql_table_name'], name='affinda_bri_sql_tab_9de90f_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaltable',
            constraint=models.UniqueConstraint(fields=('collection', 'name'), name='unique_collection_external_table_name'),
        ),
        migrations.AddConstraint(
            model_name='externaltablecolumn',
            constraint=models.UniqueConstraint(fields=('external_table', 'name'), name='unique_external_table_column_name'),
        ),
    ]
