# Generated by Django 6.0.1 on 2026-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0008_external_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True)),
                ('encrypted', models.BooleanField(default=False, help_text='Whether the value is stored encrypted (for sensitive data)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
