# Generated by Django 6.0.1 on 2026-01-17 02:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0009_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly name for this schedule', max_length=255)),
                ('sync_type', models.CharField(choices=[('full_collection', 'Full Collection Sync'), ('selective', 'Selective Sync')], help_text='Type of sync to perform', max_length=32)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this schedule is active')),
                ('cron_expression', models.CharField(help_text="Cron expression for scheduling (e.g., '0 2 * * *' for 2am daily)", max_length=100)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this schedule was last executed', null=True)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='Calculated next run time', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master toggle for webhook processing')),
                ('secret_token', models.CharField(help_text='Secret token used in webhook URL for authentication', max_length=64, unique=True)),
                ('enabled_events', models.JSONField(blank=True, default=list, help_text='List of enabled event types')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Configuration',
                'verbose_name_plural': 'Webhook Configuration',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('document_identifier', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='sync_enabled',
            field=models.BooleanField(default=True, help_text='Whether this document should be included in selective/scheduled syncs'),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection being synced (for collection-specific syncs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_histories', to='affinda_bridge.collection'),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='documents_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='documents_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='documents_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='synchistory',
            name='total_documents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synchistory',
            name='sync_type',
            field=models.CharField(choices=[('workspaces', 'Workspaces'), ('collections', 'Collections'), ('field_definitions', 'Field Definitions'), ('documents', 'Documents'), ('full_collection', 'Full Collection Sync'), ('selective', 'Selective Sync'), ('webhook', 'Webhook Sync'), ('scheduled', 'Scheduled Sync')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='synchistory',
            index=models.Index(fields=['status'], name='affinda_bri_status_1cfea7_idx'),
        ),
        migrations.AddIndex(
            model_name='synchistory',
            index=models.Index(fields=['collection', '-started_at'], name='affinda_bri_collect_c334fc_idx'),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection to sync (required for full_collection, optional for selective)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_schedules', to='affinda_bridge.collection'),
        ),
        migrations.AddField(
            model_name='syncschedulerun',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='affinda_bridge.syncschedule'),
        ),
        migrations.AddField(
            model_name='syncschedulerun',
            name='sync_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_runs', to='affinda_bridge.synchistory'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['-received_at'], name='affinda_bri_receive_84d400_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['status'], name='affinda_bri_status_cb0063_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['event_type'], name='affinda_bri_event_t_15fa16_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['document_identifier'], name='affinda_bri_documen_bbd3da_idx'),
        ),
        migrations.AddIndex(
            model_name='syncschedule',
            index=models.Index(fields=['enabled', 'next_run_at'], name='affinda_bri_enabled_e49043_idx'),
        ),
        migrations.AddIndex(
            model_name='syncschedule',
            index=models.Index(fields=['collection'], name='affinda_bri_collect_fa1564_idx'),
        ),
        migrations.AddIndex(
            model_name='syncschedulerun',
            index=models.Index(fields=['schedule', '-started_at'], name='affinda_bri_schedul_afcd6d_idx'),
        ),
    ]
