# Generated by Django 6.0.1 on 2026-01-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0010_syncschedule_syncschedulerun_webhookconfiguration_and_more'),
        ('plugins', '0003_plugininstance_affinda_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchistory',
            name='plugin_instance',
            field=models.ForeignKey(blank=True, help_text='Plugin instance being executed (for data source syncs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_histories', to='plugins.plugininstance'),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='plugin_instance',
            field=models.ForeignKey(blank=True, help_text='Plugin instance to run (required for data_source sync type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_schedules', to='plugins.plugininstance'),
        ),
        migrations.AlterField(
            model_name='synchistory',
            name='sync_type',
            field=models.CharField(choices=[('workspaces', 'Workspaces'), ('collections', 'Collections'), ('field_definitions', 'Field Definitions'), ('documents', 'Documents'), ('full_collection', 'Full Collection Sync'), ('selective', 'Selective Sync'), ('webhook', 'Webhook Sync'), ('scheduled', 'Scheduled Sync'), ('data_source', 'Data Source Sync')], max_length=32),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='sync_type',
            field=models.CharField(choices=[('full_collection', 'Full Collection Sync'), ('selective', 'Selective Sync'), ('data_source', 'Data Source Sync')], help_text='Type of sync to perform', max_length=32),
        ),
        migrations.AddIndex(
            model_name='syncschedule',
            index=models.Index(fields=['plugin_instance'], name='affinda_bri_plugin__b75aff_idx'),
        ),
    ]
