# Generated by Django 6.0.1 on 2026-01-18 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0011_synchistory_plugin_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('document_identifier', models.CharField(blank=True, help_text='Document identifier if this log entry relates to a specific document', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured data (exception details, API response, etc.)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sync_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='affinda_bridge.synchistory')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['sync_history', 'timestamp'], name='affinda_bri_sync_hi_8dc302_idx'), models.Index(fields=['sync_history', 'level'], name='affinda_bri_sync_hi_b62f13_idx'), models.Index(fields=['document_identifier'], name='affinda_bri_documen_7c1927_idx')],
            },
        ),
    ]
