# Generated by Django 6.0.1 on 2026-01-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0012_synclogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltablecolumn',
            name='default_value',
            field=models.CharField(blank=True, help_text='Default value for the column (stored as string, converted to appropriate type)', max_length=255, null=True),
        ),
    ]
