# Generated by Django 6.0.1 on 2026-01-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0013_add_default_value_to_external_table_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionview',
            name='include_external_table_columns',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of ExternalTable IDs to selected column IDs. Empty list = all columns.'),
        ),
    ]
