# Generated by Django 6.0.1 on 2026-01-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affinda_bridge', '0014_add_include_external_table_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fielddefinition',
            options={'ordering': ['collection', 'name']},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['name']},
        ),
    ]
